jugador_index:
    path:     /
    defaults: { _controller: "AUCBundle:Jugador:index" }
    methods:  GET

jugador_show:
    path:     /{id}/show
    defaults: { _controller: "AUCBundle:Jugador:show" }
    methods:  GET

jugador_new:
    path:     /new
    defaults: { _controller: "AUCBundle:Jugador:new" }
    methods:  [GET, POST]

jugador_edit:
    path:     /{id}/edit
    defaults: { _controller: "AUCBundle:Jugador:edit" }
    methods:  [GET, POST]

jugador_delete:
    path:     /{id}/delete
    defaults: { _controller: "AUCBundle:Jugador:delete" }
    methods:  [GET, POST, DELETE]
