auc:
    resource: "@AUCBundle/Resources/config/routing.yml"
    prefix:   /

jugador:
    resource: "@AUCBundle/Resources/config/routing/jugador.yml"
    prefix:   /admin/jugadores

entrenador:
    resource: "@AUCBundle/Resources/config/routing/entrenador.yml"
    prefix:   /admin/entrenadores

noticia:
    resource: "@AUCBundle/Resources/config/routing/noticia.yml"
    prefix:   /admin/noticias

equipo:
    resource: "@AUCBundle/Resources/config/routing/equipo.yml"
    prefix:   /admin/equipos

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
